// src/utils/mockData.js
// Centralized mock data for Campus Information Assistant (Phase 1 Frontend Presentation)

export const currentUser = {
  id: 'STU-2022-CSE-084',
  name: 'Rahul Sharma',
  role: 'student',
  roleTitle: 'Student',
  program: 'B.Tech Computer Science & Engineering',
  department: 'Computer Science & Engineering',
  semester: '6th Semester (3rd Year)',
  section: 'CSE-B',
  rollNo: '22CS084',
  email: 'rahul.sharma@campushub.edu',
  phone: '+91 98765 43210',
  admissionYear: '2022',
  expectedGraduation: '2026',
  cgpa: '8.74',
  attendance: '89.5%',
  avatar: '/assets/student_rahul.jpg',
  advisor: 'Dr. S. K. Venkataraman',
  address: 'Room 304, Boys Hostel Block-B, University Campus',
};

export const dashboardStats = [
  {
    id: 'notices',
    count: 12,
    label: 'New Notices',
    iconName: 'FileText',
    colorTheme: 'blue',
    bgLight: 'bg-blue-50/80',
    borderLight: 'border-blue-200/80',
    iconBg: 'bg-blue-100 text-blue-600',
    textColor: 'text-blue-950',
    link: '/student/notices',
  },
  {
    id: 'events',
    count: 3,
    label: 'Upcoming Events',
    iconName: 'Calendar',
    colorTheme: 'green',
    bgLight: 'bg-emerald-50/80',
    borderLight: 'border-emerald-200/80',
    iconBg: 'bg-emerald-100 text-emerald-600',
    textColor: 'text-emerald-950',
    link: '/student/events',
  },
  {
    id: 'classes',
    count: 0,
    label: "Today's Classes",
    iconName: 'Clock',
    colorTheme: 'purple',
    bgLight: 'bg-purple-50/80',
    borderLight: 'border-purple-200/80',
    iconBg: 'bg-purple-100 text-purple-600',
    textColor: 'text-purple-950',
    link: '/student/timetable',
  },
  {
    id: 'exams',
    count: 2,
    label: 'Upcoming Exams',
    iconName: 'ClipboardList',
    colorTheme: 'amber',
    bgLight: 'bg-amber-50/80',
    borderLight: 'border-amber-200/80',
    iconBg: 'bg-amber-100 text-amber-600',
    textColor: 'text-amber-950',
    link: '/student/examinations',
  },
];

export const latestNotices = [
  {
    id: 'NTC-101',
    title: 'Mid-Semester Exam Schedule Released',
    department: 'Examination Cell',
    date: 'Oct 22, 2024',
    category: 'Examination',
    priority: 'Important',
    priorityColor: 'bg-rose-50 text-rose-600 border-rose-200',
    iconColor: 'bg-blue-50 text-blue-600',
    iconName: 'Megaphone',
    description: 'The schedule for the Autumn Semester Mid-Term Examinations (AY 2024-25) is now available. Students must download admit slips before Oct 25.',
  },
  {
    id: 'NTC-102',
    title: 'Workshop on AI & Machine Learning',
    department: 'CSE Department',
    date: 'Oct 22, 2024',
    category: 'Event',
    priority: 'Event',
    priorityColor: 'bg-purple-50 text-purple-600 border-purple-200',
    iconColor: 'bg-purple-50 text-purple-600',
    iconName: 'Laptop',
    description: 'Hands-on bootcamp on Deep Learning and Transformer models by Google Developer Experts. Registration open till Oct 24.',
  },
  {
    id: 'NTC-103',
    title: 'Campus Placement Drive 2024',
    department: 'Training & Placement Cell',
    date: 'Oct 20, 2024',
    category: 'Placement',
    priority: 'Placement',
    priorityColor: 'bg-emerald-50 text-emerald-600 border-emerald-200',
    iconColor: 'bg-emerald-50 text-emerald-600',
    iconName: 'Target',
    description: 'Eligible 3rd & 4th-year students are invited to register for upcoming multinational tech placement drives starting next week.',
  },
  {
    id: 'NTC-104',
    title: 'Library Timing Update',
    department: 'Central Library',
    date: 'Oct 19, 2024',
    category: 'General',
    priority: 'General',
    priorityColor: 'bg-amber-50 text-amber-700 border-amber-200',
    iconColor: 'bg-amber-50 text-amber-600',
    iconName: 'BookOpen',
    description: 'In view of mid-term examinations, the Central Library will remain open until 11:30 PM on all weekdays and until 8:00 PM on weekends.',
  },
  {
    id: 'NTC-105',
    title: 'Annual Sports Meet Trials Notice',
    department: 'Sports Council',
    date: 'Oct 18, 2024',
    category: 'General',
    priority: 'General',
    priorityColor: 'bg-slate-50 text-slate-600 border-slate-200',
    iconColor: 'bg-indigo-50 text-indigo-600',
    iconName: 'Activity',
    description: 'Inter-department athletic and sports trials for Football, Cricket, Badminton, and Table Tennis commence this Saturday at University Grounds.',
  },
  {
    id: 'NTC-106',
    title: 'Scholarship Application Verification Deadline',
    department: 'Dean Student Affairs',
    date: 'Oct 15, 2024',
    category: 'Academic',
    priority: 'Important',
    priorityColor: 'bg-rose-50 text-rose-600 border-rose-200',
    iconColor: 'bg-rose-50 text-rose-600',
    iconName: 'FileCheck',
    description: 'All post-matric and merit scholarship applicants must submit attested copies of income and caste certificates before Oct 28.',
  },
];

export const upcomingEvents = [
  {
    id: 'EVT-201',
    day: '25',
    month: 'OCT',
    title: 'Tech Talk: Future of AI',
    venue: 'CSE Seminar Hall',
    time: '10:00 AM - 12:00 PM',
    dotColor: 'bg-blue-500',
    category: 'Technical',
    department: 'CSE Department',
    description: 'Industry keynote on Generative AI architectures and enterprise applications delivered by senior AI research directors.',
  },
  {
    id: 'EVT-202',
    day: '28',
    month: 'OCT',
    title: 'Hackathon 2024',
    venue: 'Main Auditorium',
    time: '09:00 AM - 06:00 PM',
    dotColor: 'bg-purple-500',
    category: 'Technical',
    department: 'College Event',
    description: 'A 24-hour inter-college code hackathon solving Smart Campus, Sustainability, and Healthcare challenges with prizes worth 2 Lakhs.',
  },
  {
    id: 'EVT-203',
    day: '02',
    month: 'NOV',
    title: 'Cultural Fest',
    venue: 'College Ground',
    time: '10:00 AM - 10:00 PM',
    dotColor: 'bg-emerald-500',
    category: 'Cultural',
    department: 'Cultural Committee',
    description: 'Annual cultural extravaganza featuring battle of the bands, classical dances, drama, food trucks, and celebrity musical night.',
  },
  {
    id: 'EVT-204',
    day: '10',
    month: 'NOV',
    title: 'Alumni Interaction',
    venue: 'Online (Google Meet)',
    time: '04:00 PM - 05:30 PM',
    dotColor: 'bg-amber-500',
    category: 'Seminar',
    department: 'Alumni Relations',
    description: 'Interactive career guidance session with alumni working at Google, Microsoft, and Amazon on global career paths and interview prep.',
  },
  {
    id: 'EVT-205',
    day: '15',
    month: 'NOV',
    title: 'Cybersecurity Bootcamp',
    venue: 'Lab 4, Tech Block',
    time: '01:00 PM - 04:00 PM',
    dotColor: 'bg-indigo-500',
    category: 'Workshop',
    department: 'IT Department',
    description: 'Ethical hacking and network defense practical lab covering packet inspection, vulnerability assessment, and OWASP Top 10.',
  },
];

export const quickLinks = [
  {
    id: 'ql-exam',
    title: 'Exam Form',
    iconName: 'FileEdit',
    bg: 'bg-rose-50/70 hover:bg-rose-100/80',
    text: 'text-rose-700',
    iconColor: 'text-rose-500',
    link: '/student/examinations',
  },
  {
    id: 'ql-results',
    title: 'Results',
    iconName: 'BarChart2',
    bg: 'bg-emerald-50/70 hover:bg-emerald-100/80',
    text: 'text-emerald-700',
    iconColor: 'text-emerald-500',
    link: '/student/examinations',
  },
  {
    id: 'ql-calendar',
    title: 'Academic Calendar',
    iconName: 'CalendarCheck',
    bg: 'bg-blue-50/70 hover:bg-blue-100/80',
    text: 'text-blue-700',
    iconColor: 'text-blue-500',
    link: '/student/documents',
  },
  {
    id: 'ql-syllabus',
    title: 'Syllabus',
    iconName: 'Book',
    bg: 'bg-purple-50/70 hover:bg-purple-100/80',
    text: 'text-purple-700',
    iconColor: 'text-purple-500',
    link: '/student/documents',
  },
  {
    id: 'ql-papers',
    title: 'Previous Papers',
    iconName: 'FileText',
    bg: 'bg-amber-50/70 hover:bg-amber-100/80',
    text: 'text-amber-800',
    iconColor: 'text-amber-600',
    link: '/student/documents',
  },
  {
    id: 'ql-directory',
    title: 'Contact Directory',
    iconName: 'PhoneCall',
    bg: 'bg-teal-50/70 hover:bg-teal-100/80',
    text: 'text-teal-700',
    iconColor: 'text-teal-500',
    link: '/student/profile',
  },
];

export const aiSuggestedPrompts = [
  'When is my next exam?',
  'Show CSE department notices',
  'What are the upcoming events?',
  'How can I apply for exam form?',
];

export const mockAiResponses = {
  'When is my next exam?':
    'According to the official exam schedule published by the Examination Cell, your next examination is **Database Management Systems (CS-601)** scheduled on **Wednesday, 25 October 2024 at 10:00 AM** in **Room 302, Academic Block A**.',
  'Show CSE department notices':
    'Here are the active CSE department notices:\n1. **Workshop on AI & Machine Learning** (Oct 22) - Registration open for hands-on transformers session.\n2. **Mid-Semester Project Review Dates** (Oct 16) - Submissions due by Friday.\n3. **Lab 3 Maintenance Notice** (Oct 14) - Lab 3 reserved for OS practicals.',
  'What are the upcoming events?':
    'Top upcoming campus events:\n• **Tech Talk: Future of AI** — 25 Oct at CSE Seminar Hall (10 AM)\n• **Hackathon 2024** — 28 Oct in Main Auditorium (9 AM - 6 PM)\n• **Cultural Fest 2024** — 02 Nov at College Grounds\n• **Alumni Interaction** — 10 Nov via Google Meet',
  'How can I apply for exam form?':
    'To submit your exam form:\n1. Navigate to **Examinations** in the sidebar.\n2. Select **Exam Forms** tab.\n3. Verify your enrolled course credits.\n4. Click **Apply for Mid-Term Examination** and complete fee payment confirmation before Oct 25, 2024.',
  default:
    'Based on campus database records for B.Tech CSE (3rd Year): Information has been retrieved from the authoritative University Portal. You can ask about exam timetables, notices, faculty hours, attendance, or download syllabus documents.',
};

export const weeklyTimetable = {
  Monday: [
    { subject: 'Database Management Systems', code: 'CS-601', faculty: 'Dr. S. K. Venkataraman', room: 'LH-301', time: '09:00 AM - 10:00 AM', type: 'Lecture' },
    { subject: 'Computer Networks', code: 'CS-602', faculty: 'Prof. Ananya Gupta', room: 'LH-302', time: '10:15 AM - 11:15 AM', type: 'Lecture' },
    { subject: 'Operating Systems Lab', code: 'CS-605P', faculty: 'Er. Rohan Mehta', room: 'Software Lab 2', time: '11:30 AM - 01:30 PM', type: 'Lab' },
    { subject: 'Artificial Intelligence', code: 'CS-603', faculty: 'Dr. Neha Kulkarni', room: 'LH-301', time: '02:30 PM - 03:30 PM', type: 'Lecture' },
  ],
  Tuesday: [
    { subject: 'Compiler Design', code: 'CS-604', faculty: 'Prof. Rajesh Rao', room: 'LH-303', time: '09:00 AM - 10:00 AM', type: 'Lecture' },
    { subject: 'Artificial Intelligence', code: 'CS-603', faculty: 'Dr. Neha Kulkarni', room: 'LH-301', time: '10:15 AM - 11:15 AM', type: 'Lecture' },
    { subject: 'DBMS Laboratory', code: 'CS-606P', faculty: 'Dr. S. K. Venkataraman', room: 'Database Lab', time: '11:30 AM - 01:30 PM', type: 'Lab' },
    { subject: 'Open Elective (IoT)', code: 'OE-601', faculty: 'Dr. Praveen Joshi', room: 'LH-204', time: '02:30 PM - 03:30 PM', type: 'Lecture' },
  ],
  Wednesday: [
    { subject: 'Computer Networks', code: 'CS-602', faculty: 'Prof. Ananya Gupta', room: 'LH-302', time: '09:00 AM - 10:00 AM', type: 'Lecture' },
    { subject: 'Database Management Systems', code: 'CS-601', faculty: 'Dr. S. K. Venkataraman', room: 'LH-301', time: '10:15 AM - 11:15 AM', type: 'Lecture' },
    { subject: 'Software Engineering', code: 'CS-605', faculty: 'Dr. Kavita Verma', room: 'LH-301', time: '11:30 AM - 12:30 PM', type: 'Lecture' },
    { subject: 'Mentorship & Project Hour', code: 'CS-607', faculty: 'Department Mentors', room: 'Seminar Room', time: '02:00 PM - 04:00 PM', type: 'Tutorial' },
  ],
  Thursday: [
    { subject: 'Artificial Intelligence', code: 'CS-603', faculty: 'Dr. Neha Kulkarni', room: 'LH-301', time: '09:00 AM - 10:00 AM', type: 'Lecture' },
    { subject: 'Compiler Design', code: 'CS-604', faculty: 'Prof. Rajesh Rao', room: 'LH-303', time: '10:15 AM - 11:15 AM', type: 'Lecture' },
    { subject: 'Networks Laboratory', code: 'CS-607P', faculty: 'Prof. Ananya Gupta', room: 'Network Lab', time: '11:30 AM - 01:30 PM', type: 'Lab' },
    { subject: 'Aptitude & Soft Skills', code: 'TR-601', faculty: 'Placement Cell', room: 'Audi 2', time: '02:30 PM - 03:30 PM', type: 'Skill' },
  ],
  Friday: [
    { subject: 'Database Management Systems', code: 'CS-601', faculty: 'Dr. S. K. Venkataraman', room: 'LH-301', time: '09:00 AM - 10:00 AM', type: 'Lecture' },
    { subject: 'Software Engineering', code: 'CS-605', faculty: 'Dr. Kavita Verma', room: 'LH-301', time: '10:15 AM - 11:15 AM', type: 'Lecture' },
    { subject: 'Computer Networks', code: 'CS-602', faculty: 'Prof. Ananya Gupta', room: 'LH-302', time: '11:30 AM - 12:30 PM', type: 'Lecture' },
    { subject: 'Library & Research Hour', code: 'RS-601', faculty: 'Faculty Advisors', room: 'Central Library', time: '02:00 PM - 04:00 PM', type: 'Research' },
  ],
  Saturday: [
    { subject: 'Industry Seminar Series', code: 'SEM-601', faculty: 'Guest Lecturers', room: 'Main Audi', time: '10:00 AM - 12:00 PM', type: 'Seminar' },
    { subject: 'Club & Co-Curricular Activities', code: 'CCA-601', faculty: 'Club Coordinators', room: 'Student Center', time: '01:00 PM - 03:00 PM', type: 'Activity' },
  ],
};

export const examinationData = {
  upcoming: [
    {
      subject: 'Database Management Systems',
      code: 'CS-601',
      semester: '6th Semester',
      date: 'Oct 25, 2024',
      time: '10:00 AM - 01:00 PM',
      venue: 'Block A, Hall 302',
      status: 'Upcoming',
      badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    },
    {
      subject: 'Computer Networks',
      code: 'CS-602',
      semester: '6th Semester',
      date: 'Oct 29, 2024',
      time: '10:00 AM - 01:00 PM',
      venue: 'Block A, Hall 304',
      status: 'Upcoming',
      badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    },
    {
      subject: 'Compiler Design',
      code: 'CS-604',
      semester: '6th Semester',
      date: 'Nov 04, 2024',
      time: '10:00 AM - 01:00 PM',
      venue: 'Block B, Hall 101',
      status: 'Upcoming',
      badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    },
    {
      subject: 'Artificial Intelligence',
      code: 'CS-603',
      semester: '6th Semester',
      date: 'Nov 08, 2024',
      time: '10:00 AM - 01:00 PM',
      venue: 'Block A, Hall 302',
      status: 'Upcoming',
      badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    },
  ],
  forms: [
    {
      id: 'EF-2024-01',
      title: 'Autumn Regular End-Term Exam Registration',
      deadline: 'Oct 30, 2024',
      fee: '₹1,500',
      status: 'Open',
      badge: 'Active Registration',
      description: 'Mandatory exam registration for all eligible 6th Semester B.Tech students.',
    },
    {
      id: 'EF-2024-02',
      title: 'Improvement / Backlog Exam Form Form-B',
      deadline: 'Nov 05, 2024',
      fee: '₹750 / Subject',
      status: 'Open',
      badge: 'Backlog Only',
      description: 'Registration form for repeating previous odd semester backlog papers.',
    },
  ],
  importantDates: [
    { event: 'Admit Card Hall Ticket Generation', date: 'Oct 23, 2024' },
    { event: 'Practical / Lab Viva Commencement', date: 'Oct 20, 2024' },
    { event: 'Theory Mid-Semester Exams', date: 'Oct 25 - Nov 10, 2024' },
    { event: 'Tentative Result Declaration', date: 'Dec 05, 2024' },
  ],
  results: [
    { semester: '5th Semester (Spring 2024)', sgpa: '8.82', cgpa: '8.74', credits: '24/24', status: 'Passed (Distinction)', releaseDate: 'Jun 18, 2024' },
    { semester: '4th Semester (Autumn 2023)', sgpa: '8.65', cgpa: '8.71', credits: '24/24', status: 'Passed (Distinction)', releaseDate: 'Jan 22, 2024' },
    { semester: '3rd Semester (Spring 2023)', sgpa: '8.90', cgpa: '8.75', credits: '26/26', status: 'Passed (Distinction)', releaseDate: 'Jun 12, 2023' },
  ],
  guidelines: [
    'Students must carry their official University Student ID Card and printed Admit Slip.',
    'Electronic gadgets, smartwatches, and programmable calculators are strictly prohibited.',
    'Candidates must report to their assigned hall 20 minutes prior to exam commencement.',
    'No candidate will be allowed to exit the examination hall during the first 60 minutes.',
  ],
};

export const campusDocuments = [
  {
    id: 'DOC-301',
    title: 'Academic Calendar (AY 2024-2025)',
    category: 'Academic',
    department: 'Dean Academic Affairs',
    date: 'Aug 10, 2024',
    fileType: 'PDF',
    size: '1.4 MB',
    downloads: 1420,
  },
  {
    id: 'DOC-302',
    title: 'B.Tech CSE Full 8-Semester Syllabus Scheme',
    category: 'Academic',
    department: 'CSE Department',
    date: 'Jul 28, 2024',
    fileType: 'PDF',
    size: '3.8 MB',
    downloads: 980,
  },
  {
    id: 'DOC-303',
    title: 'Autumn 2024 Examination Guidelines & Code of Conduct',
    category: 'Examination',
    department: 'Examination Cell',
    date: 'Oct 02, 2024',
    fileType: 'PDF',
    size: '890 KB',
    downloads: 750,
  },
  {
    id: 'DOC-304',
    title: 'Previous Year Question Papers Collection (CS 6th Sem)',
    category: 'Examination',
    department: 'Central Library',
    date: 'Sep 15, 2024',
    fileType: 'ZIP',
    size: '12.4 MB',
    downloads: 1850,
  },
  {
    id: 'DOC-305',
    title: 'Hostel Re-allotment & Mess Rules Circular',
    category: 'Circulars',
    department: 'Chief Warden Office',
    date: 'Aug 22, 2024',
    fileType: 'PDF',
    size: '620 KB',
    downloads: 410,
  },
  {
    id: 'DOC-306',
    title: 'Bonafide Certificate & No Dues Application Form',
    category: 'Forms',
    department: 'Registrar Office',
    date: 'Jul 15, 2024',
    fileType: 'DOCX',
    size: '145 KB',
    downloads: 890,
  },
  {
    id: 'DOC-307',
    title: 'Campus Wi-Fi & VPN Access Setup Manual',
    category: 'Guidelines',
    department: 'IT Infrastructure Center',
    date: 'Sep 01, 2024',
    fileType: 'PDF',
    size: '1.1 MB',
    downloads: 1220,
  },
  {
    id: 'DOC-308',
    title: 'Anti-Ragging Undertaking & Safety Policy Handout',
    category: 'Guidelines',
    department: 'Student Affairs',
    date: 'Jul 10, 2024',
    fileType: 'PDF',
    size: '510 KB',
    downloads: 2100,
  },
];

export const searchMockDatabase = [
  {
    id: 'res-1',
    title: 'CSE 3rd Year (6th Semester) Class Timetable',
    category: 'Timetable',
    department: 'CSE Department',
    date: 'Updated Oct 2024',
    snippet: 'Full weekly schedule for sections CSE-A, CSE-B, and CSE-C including DBMS, CN, AI, and laboratory hours in Software Lab 2.',
    url: '/student/timetable',
  },
  {
    id: 'res-2',
    title: 'Mid-Semester Exam Schedule 2024',
    category: 'Examination',
    department: 'Examination Cell',
    date: 'Oct 22, 2024',
    snippet: 'Complete timetable of mid-term examinations starting Oct 25. Seat allotments and hall tickets available for download.',
    url: '/student/examinations',
  },
  {
    id: 'res-3',
    title: 'Workshop on Artificial Intelligence & Machine Learning',
    category: 'Events',
    department: 'CSE Department',
    date: 'Oct 22, 2024',
    snippet: 'Two-day intensive workshop covering Deep Learning, PyTorch, Large Language Models, and practical GPU computing in CSE Seminar Hall.',
    url: '/student/events',
  },
  {
    id: 'res-4',
    title: 'Database Management Systems (CS-601) Course Syllabus',
    category: 'Documents',
    department: 'CSE Department',
    date: 'Aug 2024',
    snippet: 'Comprehensive curriculum outline for relational algebra, SQL optimization, indexing, transaction ACID properties, and distributed databases.',
    url: '/student/documents',
  },
  {
    id: 'res-5',
    title: 'Campus Placement Drive 2024 Registration',
    category: 'Notices',
    department: 'Training & Placement Cell',
    date: 'Oct 20, 2024',
    snippet: 'Drive registrations open for B.Tech CSE, IT, and ECE students having 7.0+ CGPA. Tech aptitude rounds begin next week.',
    url: '/student/notices',
  },
  {
    id: 'res-6',
    title: 'Central Library Extended Study Hours & Digital Catalogue',
    category: 'Notices',
    department: 'Central Library',
    date: 'Oct 19, 2024',
    snippet: 'Central Library will operate with extended timings up to 11:30 PM. Access IEEE Xplore, ACM Digital Library, and Springer links.',
    url: '/student/notices',
  },
];

export const notificationsList = [
  { id: 'notif-1', title: 'Admit Card Generated', time: '10 mins ago', unread: true, link: '/student/examinations' },
  { id: 'notif-2', title: 'CSE Workshop Registration Confirmed', time: '2 hours ago', unread: true, link: '/student/events' },
  { id: 'notif-3', title: 'Library Book Due in 2 Days', time: 'Yesterday', unread: false, link: '/student/notices' },
  { id: 'notif-4', title: 'Holiday Declared for Diwali Break', time: '3 days ago', unread: false, link: '/student/notices' },
];

export const facultyRoleData = {
  name: 'Dr. S. K. Venkataraman',
  designation: 'Professor & Head of Academic Council',
  department: 'Computer Science & Engineering',
  stats: [
    { label: 'My Assigned Courses', count: 3, icon: 'BookOpen', color: 'blue' },
    { label: 'Active Students', count: 184, icon: 'Users', color: 'green' },
    { label: 'Pending Evaluations', count: 42, icon: 'CheckSquare', color: 'purple' },
    { label: 'Department Notices', count: 8, icon: 'Bell', color: 'amber' },
  ],
  myCourses: [
    { code: 'CS-601', title: 'Database Management Systems', section: 'CSE-B', students: 64, room: 'LH-301' },
    { code: 'CS-802', title: 'Advanced Distributed Systems', section: 'CSE-A', students: 58, room: 'LH-402' },
    { code: 'CS-606P', title: 'Database Systems Laboratory', section: 'CSE-B', students: 62, room: 'DB Lab' },
  ],
};

export const hodRoleData = {
  name: 'Dr. Arvinder Singh',
  designation: 'Head of Department',
  department: 'Computer Science & Engineering',
  stats: [
    { label: 'Total Faculty Members', count: 28, icon: 'Users', color: 'blue' },
    { label: 'Total Enrolled Students', count: 740, icon: 'GraduationCap', color: 'green' },
    { label: 'Active Batches', count: 8, icon: 'Layers', color: 'purple' },
    { label: 'Department Notices', count: 14, icon: 'Megaphone', color: 'amber' },
  ],
};

export const deanRoleData = {
  name: 'Prof. Meenakshi Sundaram',
  designation: 'Dean of Academic Affairs',
  stats: [
    { label: 'Academic Departments', count: 9, icon: 'Building', color: 'blue' },
    { label: 'Total Enrolled Students', count: 4820, icon: 'Users', color: 'green' },
    { label: 'Accredited Programs', count: 14, icon: 'Award', color: 'purple' },
    { label: 'Senate Circulars Issued', count: 26, icon: 'FileText', color: 'amber' },
  ],
};

export const examCellData = {
  name: 'Prof. Ramesh Chander',
  designation: 'Controller of Examinations',
  stats: [
    { label: 'Active Exam Schedules', count: 6, icon: 'Calendar', color: 'blue' },
    { label: 'Hall Tickets Issued', count: 3410, icon: 'CreditCard', color: 'green' },
    { label: 'Exam Centers Ready', count: 24, icon: 'MapPin', color: 'purple' },
    { label: 'Pending Result Audits', count: 4, icon: 'CheckCircle', color: 'amber' },
  ],
};

export const adminRoleData = {
  name: 'System Administrator',
  designation: 'Central IT Administration',
  stats: [
    { label: 'Total User Accounts', count: 5240, icon: 'Users', color: 'blue' },
    { label: 'Active Sessions Today', count: 1420, icon: 'Activity', color: 'green' },
    { label: 'System Health', count: '99.98%', icon: 'Server', color: 'emerald' },
    { label: 'Pending Access Requests', count: 7, icon: 'Shield', color: 'amber' },
  ],
};
